services:
  - type: web
    name: trabajo-de-grado
    env: python
    buildCommand: |
      set -e # Exit immediately if a command exits with a non-zero status.
      echo "--- Starting build in $(pwd) ---"
      git submodule update --init --recursive

      # Install Flutter
      echo "--- Installing Flutter ---"
      git clone https://github.com/flutter/flutter.git -b stable --depth 1 /tmp/flutter
      export PATH="/tmp/flutter/bin:$PATH"

      # Build Flutter web app
      echo "--- Building Flutter web app ---"
      cd frontend
      flutter config --enable-web
      flutter pub get
      flutter build web --release
      cd ..

      # Install Python dependencies
      echo "--- Installing Python dependencies ---"
      pip install -r requirements.txt
      echo "--- Build finished ---"
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    pythonVersion: 3.10
