services:
  - type: web
    name: trabajo-de-grado
    env: python
    buildCommand: |
      set -e # Exit immediately if a command exits with a non-zero status.
      echo "--- Starting build in $(pwd) ---"
      git submodule update --init --recursive
      # Create necessary directory structure for FastAPI to run without errors
      echo "--- Creating directory structure for Flutter web assets ---"
      mkdir -p frontend/build/web/assets
      # Install Python dependencies
      echo "--- Installing Python dependencies ---"
      pip install -r requirements.txt
      echo "--- Build finished ---"
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    pythonVersion: 3.10
