services:
  - type: web
    name: trabajo-de-grado
    env: python
    buildCommand: |
      git submodule update --init --recursive
      pip install -r requirements.txt
      mkdir -p Real-ESRGAN/weights
      if [ ! -f Real-ESRGAN/weights/RealESRGAN_x4plus.pth ]; then
        curl -L -o Real-ESRGAN/weights/RealESRGAN_x4plus.pth https://github.com/xinntao/Real-ESRGAN/releases/download/v0.1.0/RealESRGAN_x4plus.pth
      fi
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    pythonVersion: 3.10
